export var font, vowels, consonants, others

export default class Alphabet {
    constructor() {
        font = new Map()
        vowels = new Map()
        consonants = new Map()
        others = new Map()
    }

    initializeConvert() {
        font.set('A', 'Ⲁ')
        font.set('a', 'ⲁ')
        font.set('B', 'Ⲃ')
        font.set('b', 'ⲃ')
        font.set('G', 'Ⲅ')
        font.set('g', 'ⲅ')
        font.set('D', 'Ⲇ')
        font.set('d', 'ⲇ')
        font.set('E', 'Ⲉ')
        font.set('e', 'ⲉ')
        font.set('Z', 'Z')
        font.set('z', 'ⲍ')
        font.set('Y', 'Ⲏ')
        font.set('y', 'ⲏ')
        font.set(':', 'Ⲑ')
        font.set(';', 'ⲑ')
        font.set('I', 'Ⲓ')
        font.set('i', 'ⲓ')
        font.set('K', 'K')
        font.set('k', 'ⲕ')
        font.set('L', 'Ⲗ')
        font.set('l', 'ⲗ')
        font.set('M', 'Ⲙ')
        font.set('m', 'ⲙ')
        font.set('N', 'Ⲛ')
        font.set('n', 'ⲛ')
        font.set('X', 'Ⲝ')
        font.set('x', 'ⲝ')
        font.set('O', 'Ⲟ')
        font.set('o', 'ⲟ')
        font.set('P', 'Ⲡ')
        font.set('p', 'ⲡ')
        font.set('R', 'Ⲣ')
        font.set('r', 'ⲣ')
        font.set('C', 'Ⲥ')
        font.set('c', 'ⲥ')
        font.set('T', 'Ⲧ')
        font.set('t', 'ⲧ')
        font.set('U', 'Ⲩ')
        font.set('u', 'ⲩ')
        font.set('V', 'Ⲫ')
        font.set('v', 'ⲫ')
        font.set('<', 'Ⲭ')
        font.set(',', 'ⲭ')
        font.set('\\', 'Ⲯ') // TODO: check
        font.set("'", 'ⲯ')
        font.set('W', 'Ⲱ')
        font.set('w', 'ⲱ')
        font.set('S', 'Ϣ')
        font.set('s', 'ϣ')
        font.set('F', 'Ϥ')
        font.set('f', 'ϥ')
        font.set('Q', 'Ϧ')
        font.set('q', 'ϧ')
        font.set('H', 'Ϩ')
        font.set('h', 'ϩ')
        font.set('J', 'Ϫ')
        font.set('j', 'ϫ')
        font.set('{', 'Ϭ')
        font.set('[', 'ϭ')
        font.set('}', 'Ϯ')
        font.set(']', 'ϯ')
        // special characters
        font.set('`', '\u0300')
        font.set('=', '\u0305')
        font.set('@', ':')
        font.set('&', ';')
        font.set('_', '=')
        font.set('¡', '⳪')
        // numbers
        font.set('^', 'ⲋ')
    }

    initializeTranslit() {
        vowels.set('Ⲁ', 'A')
        vowels.set('ⲁ', 'a')
        consonants.set('Ⲃ', 'V')
        consonants.set('ⲃ', 'v')
        consonants.set('Ⲅ', 'Gh')
        consonants.set('ⲅ', 'gh')
        consonants.set('Ⲇ', 'D')
        consonants.set('ⲇ', 'd')
        vowels.set('Ⲉ', 'E')
        vowels.set('ⲉ', 'e')
        consonants.set('Z', 'Z')
        consonants.set('ⲍ', 'z')
        vowels.set('Ⲏ', 'I')
        vowels.set('ⲏ', 'i')
        consonants.set('Ⲑ', 'Th')
        consonants.set('ⲑ', 'th')
        vowels.set('Ⲓ', 'E') // TODO: check
        vowels.set('ⲓ', 'i')
        consonants.set('K', 'K')
        consonants.set('ⲕ', 'k')
        consonants.set('Ⲗ', 'L')
        consonants.set('ⲗ', 'l')
        consonants.set('Ⲙ', 'M')
        consonants.set('ⲙ', 'm')
        consonants.set('Ⲛ', 'N')
        consonants.set('ⲛ', 'n')
        consonants.set('Ⲝ', 'Ks')
        consonants.set('ⲝ', 'ks')
        vowels.set('Ⲟ', 'O')
        vowels.set('ⲟ', 'o')
        consonants.set('Ⲡ', 'P')
        consonants.set('ⲡ', 'p')
        consonants.set('Ⲣ', 'R')
        consonants.set('ⲣ', 'r')
        consonants.set('Ⲥ', 'S')
        consonants.set('ⲥ', 's')
        consonants.set('Ⲧ', 'T')
        consonants.set('ⲧ', 't')
        vowels.set('Ⲩ', 'I')
        vowels.set('ⲩ', 'i')
        consonants.set('Ⲫ', 'F')
        consonants.set('ⲫ', 'f')
        consonants.set('Ⲭ', 'K')
        consonants.set('ⲭ', 'k')
        consonants.set('Ⲯ', 'Ps')
        consonants.set('ⲯ', 'ps')
        vowels.set('Ⲱ', 'O')
        vowels.set('ⲱ', 'o')
        consonants.set('Ϣ', 'Sh')
        consonants.set('ϣ', 'sh')
        consonants.set('Ϥ', 'F')
        consonants.set('ϥ', 'f')
        consonants.set('Ϧ', 'Kh')
        consonants.set('ϧ', 'kh')
        consonants.set('Ϩ', 'H')
        consonants.set('ϩ', 'h')
        consonants.set('Ϫ', 'J')
        consonants.set('ϫ', 'j')
        consonants.set('Ϭ', 'Ch')
        consonants.set('ϭ', 'ch')
        consonants.set('Ϯ', 'Ti')
        consonants.set('ϯ', 'ti')

        others.set('⳪', 'choice')
        // TODO: rest of numbers
        others.set('ⲋ', '6')
    }
}